#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'
#

cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'

cookbook 'nginx'
cookbook 'rbenv'
cookbook 'postgresql'
cookbook 'redis'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
